# Generated by Django 5.2.7 on 2025-11-01 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_client_sale_saleitem_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales', null=True)),
                ('requested_by', models.ForeignKey(help_text='Usuario que realizó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gestion.supplier')),
                ('warehouse', models.ForeignKey(help_text='Bodega destino del abastecimiento', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gestion.warehouse')),
                ('zone', models.ForeignKey(help_text='Zona específica donde se almacenará', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gestion.zone')),
            ],
            options={
                'verbose_name': 'Orden a Proveedor',
                'verbose_name_plural': 'Órdenes a Proveedores',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad solicitada')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio unitario (opcional)', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.supplierorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_items', to='gestion.product')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
            },
        ),
    ]
