# Generated by Django 5.2.7 on 2025-11-08 20:12

import gestion.models.user_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_supplierorder_supplierorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto del usuario (tamaño recomendado: 200x200px)', null=True, upload_to=gestion.models.user_profile.user_photo_upload_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio unitario (se toma del producto)', max_digits=10),
        ),
    ]
