# Generated by Django 5.2.7 on 2025-11-15 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_userprofile_phone_userprofile_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productmovement',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Movimiento de Producto', 'verbose_name_plural': 'Movimientos de Productos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['razon_social'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(default='General', help_text='Categoría del producto', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='control_por_lote',
            field=models.BooleanField(default=False, help_text='Control de inventario por lotes'),
        ),
        migrations.AddField(
            model_name='product',
            name='control_por_serie',
            field=models.BooleanField(default=False, help_text='Control de inventario por series'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_estandar',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Costo estándar del producto', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=6, default=0.0, editable=False, help_text='Costo promedio (calculado, solo lectura)', max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ean_upc',
            field=models.CharField(blank=True, help_text='Código EAN/UPC (opcional, único si se usa)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Factor de conversión entre UOM compra y venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AddField(
            model_name='product',
            name='ficha_tecnica_url',
            field=models.URLField(blank=True, help_text='URL de la ficha técnica del producto', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del producto', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='impuesto_iva',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA (ej: 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del producto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo del producto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='perishable',
            field=models.BooleanField(default=False, help_text='Producto perecedero (tiene fecha de vencimiento)'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta del producto', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='punto_reorden',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Punto de reorden (si no se especifica, usar stock_minimo)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock máximo permitido', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Stock mínimo requerido', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_compra',
            field=models.CharField(default='UN', help_text='Unidad de medida de compra (ej: UN, CAJA, KG)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_venta',
            field=models.CharField(default='UN', help_text='Unidad de medida de venta', max_length=20),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad del movimiento', max_digits=18),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='doc_referencia',
            field=models.CharField(blank=True, help_text='Documento de referencia (OC-123, FAC-456, GUIA-789, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento', null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='lote',
            field=models.CharField(blank=True, help_text='Número de lote (si aplica)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='motivo',
            field=models.TextField(blank=True, help_text='Motivo (para ajustes/devoluciones)', null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales', null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='serie',
            field=models.CharField(blank=True, help_text='Número de serie (si aplica)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Proveedor (para ingresos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='gestion.supplier'),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución'), ('transferencia', 'Transferencia')], default='ingreso', help_text='Tipo de movimiento', max_length=20),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Bodega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='gestion.warehouse'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad del proveedor', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='condiciones_pago',
            field=models.CharField(default='30 días', help_text='Condiciones de pago (ej: 30 días, contado, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacto_principal_email',
            field=models.EmailField(blank=True, help_text='Email del contacto principal', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacto_principal_nombre',
            field=models.CharField(blank=True, help_text='Nombre del contacto principal', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacto_principal_telefono',
            field=models.CharField(blank=True, help_text='Teléfono del contacto principal', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección del proveedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', help_text='Estado del proveedor', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='moneda',
            field=models.CharField(default='CLP', help_text='Moneda de transacción (ej: CLP, USD)', max_length=8),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nombre_fantasia',
            field=models.CharField(blank=True, help_text='Nombre de fantasía del proveedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pais',
            field=models.CharField(default='Chile', help_text='País del proveedor', max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social del proveedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rut_nif',
            field=models.CharField(blank=True, help_text='RUT/NIF del proveedor (único)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='Sitio web del proveedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apellidos',
            field=models.CharField(blank=True, help_text='Apellidos del usuario', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, help_text='Área o unidad del usuario', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Estado del usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_habilitado',
            field=models.BooleanField(default=False, help_text='Multi-factor authentication habilitado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombres',
            field=models.CharField(blank=True, help_text='Nombres del usuario', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre el usuario', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sesiones_activas',
            field=models.IntegerField(default=0, help_text='Número de sesiones activas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, help_text='Última vez que el usuario accedió al sistema', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre del producto', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='SKU único del producto', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='destination_zone',
            field=models.ForeignKey(blank=True, help_text='Zona de destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='gestion.zone'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='movement_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de movimiento (compatibilidad)', null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='movement_type',
            field=models.CharField(blank=True, help_text='Tipo de movimiento (compatibilidad)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='origin_zone',
            field=models.ForeignKey(blank=True, help_text='Zona de origen (para transferencias)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='gestion.zone'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='product',
            field=models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='gestion.product'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad (compatibilidad)', null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='reason',
            field=models.TextField(blank=True, help_text='Razón del movimiento (compatibilidad)', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='Email de contacto del proveedor', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre del proveedor (compatibilidad, usar razon_social)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('bodega', 'Operador de Bodega'), ('ventas', 'Operador de Ventas'), ('auditor', 'Auditor'), ('operador', 'Operador')], default='ventas', help_text='Rol del usuario en el sistema', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=6, help_text='Costo del producto para este proveedor', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_dias', models.IntegerField(default=7, help_text='Tiempo de entrega en días', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_lote', models.DecimalField(blank=True, decimal_places=6, default=1.0, help_text='Cantidad mínima de compra', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Porcentaje de descuento', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferente', models.BooleanField(default=False, help_text='Indica si es el proveedor preferente para este producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_relations', to='gestion.product')),
                ('supplier', models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='gestion.supplier')),
            ],
            options={
                'verbose_name': 'Relación Producto-Proveedor',
                'verbose_name_plural': 'Relaciones Producto-Proveedor',
                'ordering': ['-preferente', 'costo'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
