# Generated by Django 5.2.7 on 2025-11-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_product_options_alter_productmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del movimiento', null=True),
        ),
    ]
