# Generated by Django 5.2.7 on 2025-11-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_productmovement_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales (máximo 1000 caracteres)', max_length=1000, null=True),
        ),
    ]
