# Generated by Django 5.2.7 on 2025-11-22 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_make_supplier_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='Email de contacto del proveedor (requerido)', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nombre_fantasia',
            field=models.CharField(blank=True, help_text='Nombre de fantasía del proveedor (opcional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pais',
            field=models.CharField(default='Chile', help_text='País del proveedor (requerido, default: Chile)', max_length=64),
        ),
    ]
