# Generated by Django 5.2.7 on 2025-11-22 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_make_supplier_pais_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='costo',
            field=models.DecimalField(decimal_places=6, help_text='Costo del producto para este proveedor (requerido)', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='lead_time_dias',
            field=models.IntegerField(default=7, help_text='Tiempo de entrega en días (requerido, default: 7)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='preferente',
            field=models.BooleanField(default=False, help_text='Indica si es el proveedor preferente para este producto (requerido, default: False)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='condiciones_pago',
            field=models.CharField(default='30 días', help_text='Condiciones de pago (ej: 30 días, contado, etc., requerido)', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', help_text='Estado del proveedor (requerido)', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='moneda',
            field=models.CharField(default='CLP', help_text='Moneda de transacción (ej: CLP, USD, requerido)', max_length=8),
        ),
    ]
