# Generated by Django 5.2.7 on 2025-11-22 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_make_user_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(default='General', help_text='Categoría del producto (requerido)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='control_por_lote',
            field=models.BooleanField(default=False, help_text='Control de inventario por lotes (requerido, default: False)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='control_por_serie',
            field=models.BooleanField(default=False, help_text='Control de inventario por series (requerido, default: False)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Factor de conversión entre UOM compra y venta (requerido, default: 1)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='impuesto_iva',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA (requerido, ej: 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre del producto (requerido)', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='perishable',
            field=models.BooleanField(default=False, help_text='Producto perecedero (requerido, default: False)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Stock mínimo requerido (requerido, default: 0)', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom_compra',
            field=models.CharField(default='UN', help_text='Unidad de medida de compra (requerido, ej: UN, CAJA, KG)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom_venta',
            field=models.CharField(default='UN', help_text='Unidad de medida de venta (requerido)', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario (opcional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('bodega', 'Operador de Bodega'), ('ventas', 'Operador de Ventas'), ('auditor', 'Auditor'), ('operador', 'Operador')], default='ventas', help_text='Rol del usuario en el sistema (requerido)', max_length=20),
        ),
    ]
