# Generated by Django 5.2.7 on 2025-11-23 00:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_product_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodegas'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['warehouse', 'name'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Email del cliente (opcional)', max_length=150, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Nombre o Razón Social del cliente (requerido)', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono del cliente (opcional, formato chileno)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del cliente (opcional, único si se proporciona)', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(db_index=True, default='General', help_text='Categoría del producto (requerido)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre del producto (requerido)', max_length=200),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(help_text='Dirección de la bodega (requerido, máximo 500 caracteres)', max_length=500),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la bodega está activa'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text='Nombre de la bodega (requerido)', max_length=200),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la zona está activa'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(help_text='Nombre de la zona (requerido)', max_length=100),
        ),
        migrations.AlterField(
            model_name='zone',
            name='warehouse',
            field=models.ForeignKey(help_text='Bodega a la que pertenece la zona (requerido)', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='gestion.warehouse'),
        ),
    ]
