# Generated by Django 5.2.7 on 2025-11-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_add_indexes_to_product_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'quantity'], name='gestion_inv_product_7268c5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['zone', 'quantity'], name='gestion_inv_zone_id_c10d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='gestion_pro_is_acti_9b2cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'categoria'], name='gestion_pro_is_acti_c7b81d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'precio_venta'], name='gestion_pro_is_acti_16090d_idx'),
        ),
    ]
